name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Install eslint
        run:  npm install eslint eslint-config-athom

      - name: Run eslint
        uses: samuelmeuli/lint-action@v1.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Authorizes the github action via a Github token which is for this repo only (Generated automatically)
          eslint: true

