name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Install eslint
        run: NODE_ENV=development npm install eslint eslint-config-athom

      - name: Run ESLint
        run: node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
